dataset:
  data_dir: /media/hdd1/chuxiaohui/AI4Ocean_UATR/DeepShip_622
  data_type: wav_s@wav_t
  fold: 0
  num_workers: 4
  total_folds: 10
distillation:
  USE_DYNAMIC_DISTILL_WEIGHT: false
  alpha: 0.3
  distill_type: MTSKD
  learnable_alpha: true
  temperature: 2.0
  weight_type: uniform
distributed:
  backend: nccl
  gpu_ids:
  - 4
  - 5
  - 6
  - 7
  master_addr: localhost
  master_port: '37543'
model:
  num_classes: 4
  student:
    p_classifier: 0.35
    p_encoder: 0.1
    stu_seq_len: 16
  teacher:
    checkpoint_path: /media/hdd1/fubohan/Code/UATR/models/Audio_Teacher_DeepShip_622/checkpoints/Student.pth
    freeze: true
    pretrained: true
save:
  save_dir: checkpoints/cv_deepship/total_folds10_fold0_num_epochs200_weight_decay8e-05_batch_size16_lr0.0004_distill_typeMTSKD_freezeTrue_USE_DYNAMIC_DISTILL_WEIGHTFalse_p_encoder0.1_p_classifier0.35
  save_interval: 10
training:
  batch_size: 16
  log_interval: 20
  lr: 0.0004
  num_epochs: 200
  seed: 42
  weight_decay: 8.0e-05
